const DAY = 24 * 60 * 60 * 1000

export const offers = [
  {
    id: 'offer-0',
    sharePoints: 35,
    buyPoints: 70,
    expirationDate: String(Date.now() + (4.5 * DAY)),
    title: '50% Off On Wall Art',
    image: 'http://www.apimages.com/Images/Ap_Creative_Stock_Header.jpg',
    icon: 'http://diylogodesigns.com/blog/wp-content/uploads/2016/06/Nasa-Logo-Transparent-Background-download.png',
    totalUsers: 115,
    users: [
      { image: 'http://www.uncle-andrew.net/blog/pics/aaron_paul.jpg' },
      { image: 'https://i.pinimg.com/736x/de/1e/fe/de1efef55429481f3b9d8daf14686e82--beautiful-eyes-most-beautiful.jpg' },
      { image: 'https://s-media-cache-ak0.pinimg.com/736x/e9/70/67/e970671faa03af41e716cd7e63385034--unique-faces-face-reference.jpg' },
    ],
    description: 'Mauris ex, Lorem ipsum dolor sit ametconsectetur adipiscing elit. Etiam viverra tortor eget libero consectetur convallis. Sed ipsum mi, vehicula et pulvinar in, venenatis ac enim. In non velit quis tellus suscipit fermentum. Cras blandit, augue vitae cursus ullamcorper, nibh lacus dignissim ante, lobortis dapibus ante ligula ut tortor. Proin nulla augue, rutrum eget felis ac, porta faucibus ex. In congue leo neque, vel vehicula est posuere at. Sed ex urna, facilisis eget consequat ut, gravida id nulla.',
    type: 'beauty',
    location: {
      lat: 51.48,
      lng: -0.01,
    },
  },
  {
    id: 'offer-1',
    sharePoints: 20,
    expirationDate: String(Date.now() + (2 * DAY)),
    title: 'Up to 80% Off Falconry and Animal Encounter',
    image: 'http://2.bp.blogspot.com/-E_KmxExj98s/Vo0-MNSlSdI/AAAAAAAAAV0/d7hrMKw9YAA/s1600/pareja.jpg',
    icon: 'http://diylogodesigns.com/blog/wp-content/uploads/2016/05/adidas-new-logo-Transparent-Background.png',
    totalUsers: 2,
    users: [
      { image: 'https://i.pinimg.com/736x/de/1e/fe/de1efef55429481f3b9d8daf14686e82--beautiful-eyes-most-beautiful.jpg' },
      { image: 'https://s-media-cache-ak0.pinimg.com/736x/e9/70/67/e970671faa03af41e716cd7e63385034--unique-faces-face-reference.jpg' },
    ],
    description: 'Mauris ex, Lorem ipsum dolor sit ametconsectetur adipiscing elit. Etiam viverra tortor eget libero consectetur convallis. Sed ipsum mi, vehicula et pulvinar in, venenatis ac enim. In non velit quis tellus suscipit fermentum. Cras blandit, augue vitae cursus ullamcorper, nibh lacus dignissim ante, lobortis dapibus ante ligula ut tortor. Proin nulla augue, rutrum eget felis ac, porta faucibus ex. In congue leo neque, vel vehicula est posuere at. Sed ex urna, facilisis eget consequat ut, gravida id nulla.',
    type: 'beauty',
    location: {
      lat: 51.47,
      lng: -0.007,
    },
  },
  {
    id: 'offer-2',
    buyPoints: 500,
    expirationDate: String(Date.now() + (8 * DAY)),
    title: 'Up to 77% Off Cryogenic Lipolysis',
    image: 'http://somebodymarketing.com/wp-content/uploads/2013/05/Stock-Dock-House.jpg',
    icon: 'http://freepngimages.com/wp-content/uploads/2015/10/vans-logo.png',
    totalUsers: 220,
    users: [
      { image: 'https://s-media-cache-ak0.pinimg.com/736x/e9/70/67/e970671faa03af41e716cd7e63385034--unique-faces-face-reference.jpg' },
      { image: 'https://i.pinimg.com/736x/de/1e/fe/de1efef55429481f3b9d8daf14686e82--beautiful-eyes-most-beautiful.jpg' },
      { image: 'http://www.uncle-andrew.net/blog/pics/aaron_paul.jpg' },
    ],
    description: 'Mauris ex, Lorem ipsum dolor sit ametconsectetur adipiscing elit. Etiam viverra tortor eget libero consectetur convallis. Sed ipsum mi, vehicula et pulvinar in, venenatis ac enim. In non velit quis tellus suscipit fermentum. Cras blandit, augue vitae cursus ullamcorper, nibh lacus dignissim ante, lobortis dapibus ante ligula ut tortor. Proin nulla augue, rutrum eget felis ac, porta faucibus ex. In congue leo neque, vel vehicula est posuere at. Sed ex urna, facilisis eget consequat ut, gravida id nulla.',
    type: 'beauty',
    location: {
      lat: 51.46,
      lng: -0.07,
    },
  },
  {
    id: 'offer-3',
    sharePoints: 74,
    buyPoints: 158,
    expirationDate: String(Date.now() + (0.7 * DAY)),
    title: 'Up to 40% Off Afternoon Tea',
    image: 'https://ak.picdn.net/assets/cms/21c3901c18b5824f76305971fcf2cf030f1a89e7-stock-vector-elephant-flat-icon-318716621.jpg',
    icon: 'http://logos-download.com/wp-content/uploads/2016/02/Ford_logo_motor_company_transparent.png',
    totalUsers: 84,
    users: [
      { image: 'https://i.pinimg.com/736x/de/1e/fe/de1efef55429481f3b9d8daf14686e82--beautiful-eyes-most-beautiful.jpg' },
      { image: 'http://www.uncle-andrew.net/blog/pics/aaron_paul.jpg' },
      { image: 'https://s-media-cache-ak0.pinimg.com/736x/e9/70/67/e970671faa03af41e716cd7e63385034--unique-faces-face-reference.jpg' },
    ],
    description: 'Mauris ex, Lorem ipsum dolor sit ametconsectetur adipiscing elit. Etiam viverra tortor eget libero consectetur convallis. Sed ipsum mi, vehicula et pulvinar in, venenatis ac enim. In non velit quis tellus suscipit fermentum. Cras blandit, augue vitae cursus ullamcorper, nibh lacus dignissim ante, lobortis dapibus ante ligula ut tortor. Proin nulla augue, rutrum eget felis ac, porta faucibus ex. In congue leo neque, vel vehicula est posuere at. Sed ex urna, facilisis eget consequat ut, gravida id nulla.',
    type: 'beauty',
    location: {
      lat: 51.49,
      lng: -0.06,
    },
  },
  {
    id: 'offer-4',
    sharePoints: 32,
    buyPoints: 408,
    expirationDate: String(Date.now() + (1.2 * DAY)),
    title: 'Up to 31% Off Japanese Tasting Menu',
    image: 'http://skyrocketradio.com/wp-content/uploads/2016/05/unslpash-desert-road_uvsq5s.png',
    icon: 'https://vignette3.wikia.nocookie.net/ashton-games/images/9/97/Minecraft-logo-transparent-background-ut05tirq.png/revision/latest?cb=20150505163601',
    totalUsers: 21,
    users: [
      { image: 'https://i.pinimg.com/736x/de/1e/fe/de1efef55429481f3b9d8daf14686e82--beautiful-eyes-most-beautiful.jpg' },
      { image: 'http://www.uncle-andrew.net/blog/pics/aaron_paul.jpg' },
      { image: 'https://s-media-cache-ak0.pinimg.com/736x/e9/70/67/e970671faa03af41e716cd7e63385034--unique-faces-face-reference.jpg' },
    ],
    description: 'Mauris ex, Lorem ipsum dolor sit ametconsectetur adipiscing elit. Etiam viverra tortor eget libero consectetur convallis. Sed ipsum mi, vehicula et pulvinar in, venenatis ac enim. In non velit quis tellus suscipit fermentum. Cras blandit, augue vitae cursus ullamcorper, nibh lacus dignissim ante, lobortis dapibus ante ligula ut tortor. Proin nulla augue, rutrum eget felis ac, porta faucibus ex. In congue leo neque, vel vehicula est posuere at. Sed ex urna, facilisis eget consequat ut, gravida id nulla.',
    type: 'beauty',
    location: {
      lat: 51.43,
      lng: -0.04,
    },
  },
  {
    id: 'offer-5',
    sharePoints: 65,
    buyPoints: 14,
    expirationDate: String(Date.now() + (3.2 * DAY)),
    title: 'Up to 53% Off Bottomless Brunch',
    image: 'https://netdna.webdesignerdepot.com/uploads/2013/11/picjumbo.com_IMG_3130.jpg',
    icon: 'http://diylogodesigns.com/blog/wp-content/uploads/2016/05/Pizza-Hut-Logo-PNG-Transparent-Background.png',
    totalUsers: 115,
    users: [
      { image: 'https://i.pinimg.com/736x/de/1e/fe/de1efef55429481f3b9d8daf14686e82--beautiful-eyes-most-beautiful.jpg' },
      { image: 'http://www.uncle-andrew.net/blog/pics/aaron_paul.jpg' },
      { image: 'https://s-media-cache-ak0.pinimg.com/736x/e9/70/67/e970671faa03af41e716cd7e63385034--unique-faces-face-reference.jpg' },
    ],
    description: 'Mauris ex, Lorem ipsum dolor sit ametconsectetur adipiscing elit. Etiam viverra tortor eget libero consectetur convallis. Sed ipsum mi, vehicula et pulvinar in, venenatis ac enim. In non velit quis tellus suscipit fermentum. Cras blandit, augue vitae cursus ullamcorper, nibh lacus dignissim ante, lobortis dapibus ante ligula ut tortor. Proin nulla augue, rutrum eget felis ac, porta faucibus ex. In congue leo neque, vel vehicula est posuere at. Sed ex urna, facilisis eget consequat ut, gravida id nulla.',
    type: 'beauty',
    location: {
      lat: 51.41,
      lng: -0.07,
    },
  },
  {
    id: 'offer-6',
    sharePoints: 85,
    buyPoints: 35,
    expirationDate: String(Date.now() + (6.1 * DAY)),
    title: 'Up to 40% Off for peanut butter',
    image: 'https://img3.stockfresh.com/files/n/nyul/m/61/99927_stock-photo-confident-businessman.jpg',
    icon: 'http://freepngimages.com/wp-content/uploads/2016/10/netflix-logo.png',
    totalUsers: 0,
    users: [],
    description: 'Mauris ex, Lorem ipsum dolor sit ametconsectetur adipiscing elit. Etiam viverra tortor eget libero consectetur convallis. Sed ipsum mi, vehicula et pulvinar in, venenatis ac enim. In non velit quis tellus suscipit fermentum. Cras blandit, augue vitae cursus ullamcorper, nibh lacus dignissim ante, lobortis dapibus ante ligula ut tortor. Proin nulla augue, rutrum eget felis ac, porta faucibus ex. In congue leo neque, vel vehicula est posuere at. Sed ex urna, facilisis eget consequat ut, gravida id nulla.',
    type: 'beauty',
    location: {
      lat: 51.50,
      lng: 0.02,
    },
  },
  {
    id: 'offer-7',
    sharePoints: 95,
    buyPoints: 1580,
    expirationDate: String(Date.now() + (2 * DAY)),
    title: 'Get 30% discount for 2 hot-dogs with sauce',
    image: 'https://www.roiinvesting.com/wp-content/uploads/2015/09/Stock-Photos-of-Investing.jpg',
    icon: 'http://diylogodesigns.com/blog/wp-content/uploads/2016/04/Coca-Cola-Logo-PNG.png',
    totalUsers: 1,
    users: [
      { image: 'https://i.pinimg.com/736x/de/1e/fe/de1efef55429481f3b9d8daf14686e82--beautiful-eyes-most-beautiful.jpg' },
    ],
    description: 'Mauris ex, Lorem ipsum dolor sit ametconsectetur adipiscing elit. Etiam viverra tortor eget libero consectetur convallis. Sed ipsum mi, vehicula et pulvinar in, venenatis ac enim. In non velit quis tellus suscipit fermentum. Cras blandit, augue vitae cursus ullamcorper, nibh lacus dignissim ante, lobortis dapibus ante ligula ut tortor. Proin nulla augue, rutrum eget felis ac, porta faucibus ex. In congue leo neque, vel vehicula est posuere at. Sed ex urna, facilisis eget consequat ut, gravida id nulla.',
    type: 'beauty',
    location: {
      lat: 51.40,
      lng: 0.05,
    },
  },
  {
    id: 'offer-8',
    sharePoints: 20,
    buyPoints: 30,
    expirationDate: String(Date.now() + (7.05 * DAY)),
    title: 'Last chance to get a ship',
    image: 'http://media.beam.usnews.com/60/7a/95137a61496d8dac7c9141e5683d/161227-stock.jpg',
    icon: 'http://franverona.com/loadgo/logos/batman.png',
    totalUsers: 120,
    users: [
      { image: 'https://i.pinimg.com/736x/de/1e/fe/de1efef55429481f3b9d8daf14686e82--beautiful-eyes-most-beautiful.jpg' },
      { image: 'http://www.uncle-andrew.net/blog/pics/aaron_paul.jpg' },
      { image: 'https://s-media-cache-ak0.pinimg.com/736x/e9/70/67/e970671faa03af41e716cd7e63385034--unique-faces-face-reference.jpg' },
    ],
    description: 'Mauris ex, Lorem ipsum dolor sit ametconsectetur adipiscing elit. Etiam viverra tortor eget libero consectetur convallis. Sed ipsum mi, vehicula et pulvinar in, venenatis ac enim. In non velit quis tellus suscipit fermentum. Cras blandit, augue vitae cursus ullamcorper, nibh lacus dignissim ante, lobortis dapibus ante ligula ut tortor. Proin nulla augue, rutrum eget felis ac, porta faucibus ex. In congue leo neque, vel vehicula est posuere at. Sed ex urna, facilisis eget consequat ut, gravida id nulla.',
    type: 'beauty',
    location: {
      lat: 51.52,
      lng: 0.08,
    },
  },
]

export const categories = [
  {
    id: '0',
    name: 'BEAUTY & SPAS',
    sub: [
      { name: 'SKIN CARE', id: '00' },
      { name: 'HAIR REMOVAL', id: '01' },
      { name: 'NAIL SALONS', id: '02' },
      { name: 'TANNING', id: '03' },
      { name: '2SKIN CARE', id: '04' },
      { name: '2HAIR REMOVAL', id: '05' },
      { name: '2NAIL SALONS', id: '06' },
      { name: '2TANNING', id: '07' },
    ],
  },
  {
    id: '1',
    name: 'HEALTH & FITNESS',
    sub: [],
  },
  {
    id: '2',
    name: 'THINGS TO DO',
    sub: [
      { name: 'Repair home', id: '20' },
      { name: 'Swimming', id: '21' },
      { name: 'Walking', id: '22' },
    ],
  },
  {
    id: '3',
    name: 'HOME IMPROVEMENT',
    sub: [],
  },
  {
    id: '4',
    name: 'AUTOMOTIVE',
    sub: [],
  },
  {
    id: '5',
    name: 'TRAVEL',
    sub: [],
  },
  {
    id: '6',
    name: 'THINGS TO DO',
    sub: [],
  },
  {
    id: '7',
    name: 'PERSONAL SERVICES',
    sub: [],
  },
  {
    id: '8',
    name: 'RETAIL',
    sub: [],
  },
  {
    id: '9',
    name: 'EVENTS',
    sub: [],
  },
]
